// Generated by npm run gpx:import-all.
export const gpxManifest: Record<string, Record<string, string>> = {
  "6-ur-crete": {
    "ponavljajoca-trasa": "/gpx/6-ur-crete/6-ur-crete-ponavljajoca-trasa-8.2km.gpx"
  },
  "6-ur-spanovega-vrha": {
    "ponavljajoca-trasa": "/gpx/6-ur-spanovega-vrha/6-ur-spanovega-vrha-ponavljajoca-trasa-2.1km.gpx"
  },
  "7-ur-slivnice": {
    "ponavljajoca-trasa": "/gpx/7-ur-slivnice/7-ur-slivnice-ponavljajoca-trasa-3.5km.gpx"
  },
  "8-ur-sv-ane": {
    "ponavljajoca-trasa": "/gpx/8-ur-sv-ane/8-ur-sv-ane-ponavljajoca-trasa-2.7km.gpx"
  },
  "caven-run": {
    "caven-trail": "/gpx/caven-run/caven-run-caven-trail-17km.gpx",
    "caven-vertikal": "/gpx/caven-run/caven-run-caven-vertikal-4.3km.gpx"
  },
  "go4trail": {
    "go-3v": "/gpx/go4trail/go4trail-go-3v-28km.gpx",
    "go-trim": "/gpx/go4trail/go4trail-go-trim-13km.gpx",
    "go-ultra": "/gpx/go4trail/go4trail-go-ultra-64km.gpx"
  },
  "haloze-trail": {
    "trasa-1": "/gpx/haloze-trail/haloze-trail-trasa-1-14km.gpx",
    "trasa-2": "/gpx/haloze-trail/haloze-trail-trasa-2-22km.gpx"
  },
  "hg-trail-idrija": {
    "berkmandlc": "/gpx/hg-trail-idrija/hg-trail-idrija-berkmandlc-27km.gpx",
    "cipka": "/gpx/hg-trail-idrija/hg-trail-idrija-cipka-14km.gpx",
    "laufar": "/gpx/hg-trail-idrija/hg-trail-idrija-laufar-50km.gpx"
  },
  "hrastnik-trail": {
    "r12-razglednih-12": "/gpx/hrastnik-trail/hrastnik-trail-r12-razglednih-12-12km.gpx",
    "t6-turisticnih-6": "/gpx/hrastnik-trail/hrastnik-trail-t6-turisticnih-6-6km.gpx"
  },
  "julian-alps-trail-run-by-utmb": {
    "funny-10k": "/gpx/julian-alps-trail-run-by-utmb/julian-alps-trail-run-by-utmb-funny-10km.gpx",
    "i-feel-slovenia-120k": "/gpx/julian-alps-trail-run-by-utmb/julian-alps-trail-run-by-utmb-i-feel-slovenia-120k-124km.gpx",
    "intersport-speed-15k": "/gpx/julian-alps-trail-run-by-utmb/julian-alps-trail-run-by-utmb-intersport-speed-15km.gpx",
    "kranjska-gora-25k": "/gpx/julian-alps-trail-run-by-utmb/julian-alps-trail-run-by-utmb-kranjska-gora-25km.gpx",
    "lake-bled-80k": "/gpx/julian-alps-trail-run-by-utmb/julian-alps-trail-run-by-utmb-lake-bled-80km.gpx",
    "sky-trail-50k": "/gpx/julian-alps-trail-run-by-utmb/julian-alps-trail-run-by-utmb-sky-trail-50km.gpx"
  },
  "k24-ultra-trail": {
    "friday-shorty-10km": "/gpx/k24-ultra-trail/k24-ultra-trail-friday-shorty-10km.gpx",
    "gorski-maraton-50km": "/gpx/k24-ultra-trail/k24-ultra-trail-gorski-maraton-50km.gpx",
    "k24-trail-100km": "/gpx/k24-ultra-trail/k24-ultra-trail-k24-trail-100km.gpx",
    "k24-trail-24km": "/gpx/k24-ultra-trail/k24-ultra-trail-k24-trail-24km.gpx"
  },
  "kbk-trail": {
    "proga": "/gpx/kbk-trail/kbk-trail-proga-21.5km.gpx"
  },
  "knap-trail": {
    "t-douga": "/gpx/knap-trail/knap-trail-t-douga-51km.gpx",
    "t-kratka": "/gpx/knap-trail/knap-trail-t-kratka-16km.gpx",
    "t-sredna": "/gpx/knap-trail/knap-trail-t-sredna-30km.gpx"
  },
  "kocevsko-outdoor-festival": {
    "bambi-trail": "/gpx/kocevsko-outdoor-festival/kocevsko-outdoor-festival-bambi-trail-5km.gpx",
    "bear-trail": "/gpx/kocevsko-outdoor-festival/kocevsko-outdoor-festival-bear-trail-50km.gpx",
    "deer-trail": "/gpx/kocevsko-outdoor-festival/kocevsko-outdoor-festival-deer-trail-25km.gpx",
    "fox-trail": "/gpx/kocevsko-outdoor-festival/kocevsko-outdoor-festival-fox-trail-10km.gpx",
    "lynx-trail": "/gpx/kocevsko-outdoor-festival/kocevsko-outdoor-festival-lynx-trail-15km.gpx",
    "vertikal-fridrihstajn": "/gpx/kocevsko-outdoor-festival/kocevsko-outdoor-festival-vertikal-fridrihstajn-2.6km.gpx",
    "wolf-trail": "/gpx/kocevsko-outdoor-festival/kocevsko-outdoor-festival-wolf-trail-35km.gpx"
  },
  "kras-trail": {
    "dolga-razdalja": "/gpx/kras-trail/kras-trail-dolga-razdalja-52km.gpx",
    "kratka-razdalja": "/gpx/kras-trail/kras-trail-kratka-razdalja-10km.gpx",
    "srednja-razdalja": "/gpx/kras-trail/kras-trail-srednja-razdalja-29km.gpx"
  },
  "kriska-gora-trail": {
    "gams": "/gpx/kriska-gora-trail/kriska-gora-trail-gams-10km.gpx",
    "kosuta": "/gpx/kriska-gora-trail/kriska-gora-trail-kosuta-50km.gpx",
    "muflon": "/gpx/kriska-gora-trail/kriska-gora-trail-muflon-20km.gpx",
    "vertikala": "/gpx/kriska-gora-trail/kriska-gora-trail-vertikala-4km.gpx"
  },
  "lahinja-trail": {
    "duma": "/gpx/lahinja-trail/lahinja-trail-duma-9.9km.gpx",
    "republikanka": "/gpx/lahinja-trail/lahinja-trail-republikanka-31.1km.gpx",
    "velikobukovska": "/gpx/lahinja-trail/lahinja-trail-velikobukovska-18.2km.gpx"
  },
  "loncarija-tece": {
    "loncar": "/gpx/loncarija-tece/loncarija-tece-loncar-10km.gpx",
    "poticnica": "/gpx/loncarija-tece/loncarija-tece-poticnica-24km.gpx"
  },
  "obala-ultra-trail": {
    "obala-trail-11km": "/gpx/obala-ultra-trail/obala-ultra-trail-obala-trail-11km.gpx",
    "obala-trail-17km": "/gpx/obala-ultra-trail/obala-ultra-trail-obala-trail-17km.gpx",
    "obala-trail-35km": "/gpx/obala-ultra-trail/obala-ultra-trail-obala-trail-35km.gpx",
    "obala-ultra-trail-108km": "/gpx/obala-ultra-trail/obala-ultra-trail-obala-ultra-trail-108km.gpx",
    "obala-ultra-trail-64km": "/gpx/obala-ultra-trail/obala-ultra-trail-obala-ultra-trail-64km.gpx"
  },
  "podbrdo-trail-running-festival": {
    "gorski-maraton-4-obcin-gm40": "/gpx/podbrdo-trail-running-festival/podbrdo-trail-running-festival-gorski-maraton-4-obcin-gm40-40.6km.gpx",
    "graparski-trail": "/gpx/podbrdo-trail-running-festival/podbrdo-trail-running-festival-graparski-trail-23km.gpx",
    "rapallo-trail": "/gpx/podbrdo-trail-running-festival/podbrdo-trail-running-festival-rapallo-trail-10km.gpx",
    "ultra-trail-puseljc-100-utp-100": "/gpx/podbrdo-trail-running-festival/podbrdo-trail-running-festival-ultra-trail-puseljc-100-utp-100-103.8km.gpx",
    "ultra-trail-puseljc-70-utp-70": "/gpx/podbrdo-trail-running-festival/podbrdo-trail-running-festival-ultra-trail-puseljc-70-utp-70-70.1km.gpx"
  },
  "pol-sihta-na-farbanco": {
    "ponavljajoca-trasa": "/gpx/pol-sihta-na-farbanco/pol-sihta-na-farbanco-ponavljajoca-trasa-1.3km.gpx"
  },
  "ponikva4trail": {
    "trasa-tek": "/gpx/ponikva4trail/ponikva4trail-trasa-tek-23km.gpx"
  },
  "ribnica-trail": {
    "cebular-ca": "/gpx/ribnica-trail/ribnica-trail-cebular-ca-25.4km.gpx",
    "kuhavn-ca": "/gpx/ribnica-trail/ribnica-trail-kuhavn-ca-12.6km.gpx",
    "ribez-n": "/gpx/ribnica-trail/ribnica-trail-ribez-n-39.7km.gpx"
  },
  "savinjski-k6-trail": {
    "k6-trasa": "/gpx/savinjski-k6-trail/savinjski-k6-trail-k6-trasa-27km.gpx"
  },
  "slovenski-gozdarski-trail": {
    "bukev": "/gpx/slovenski-gozdarski-trail/slovenski-gozdarski-trail-bukev-34km.gpx",
    "jelka": "/gpx/slovenski-gozdarski-trail/slovenski-gozdarski-trail-jelka-14km.gpx"
  },
  "smarjeski-tek": {
    "prinovec": "/gpx/smarjeski-tek/smarjeski-tek-prinovec-8km.gpx",
    "radulja": "/gpx/smarjeski-tek/smarjeski-tek-radulja-28km.gpx",
    "toplica": "/gpx/smarjeski-tek/smarjeski-tek-toplica-19km.gpx"
  },
  "sneznik-trails": {
    "bistrska-10-ka": "/gpx/sneznik-trails/sneznik-trails-bistrska-10-ka-9.7km.gpx",
    "kozlek-trail": "/gpx/sneznik-trails/sneznik-trails-kozlek-trail-33km.gpx",
    "milanja-trail": "/gpx/sneznik-trails/sneznik-trails-milanja-trail-17km.gpx",
    "sneznik-trail": "/gpx/sneznik-trails/sneznik-trails-sneznik-trail-64.8km.gpx"
  },
  "soca-outdoor-festival": {
    "adidas-terrex-15km": "/gpx/soca-outdoor-festival/soca-outdoor-festival-adidas-terrex-15km-14.6km.gpx",
    "continental-10km": "/gpx/soca-outdoor-festival/soca-outdoor-festival-continental-10km-11.7km.gpx",
    "ford-35km": "/gpx/soca-outdoor-festival/soca-outdoor-festival-ford-35km-32.1km.gpx",
    "hempika-5km": "/gpx/soca-outdoor-festival/soca-outdoor-festival-hempika-5km-5.3km.gpx",
    "i-feel-slovenia-50km": "/gpx/soca-outdoor-festival/soca-outdoor-festival-i-feel-slovenia-50km-52.1km.gpx",
    "la-primafit-25km": "/gpx/soca-outdoor-festival/soca-outdoor-festival-la-primafit-25km-27.7km.gpx",
    "vertikal": "/gpx/soca-outdoor-festival/soca-outdoor-festival-vertikal-2km.gpx"
  },
  "trail-po-kraskih-klancih": {
    "trasa-1": "/gpx/trail-po-kraskih-klancih/trail-po-kraskih-klancih-trasa-1-12.3km.gpx",
    "trasa-2": "/gpx/trail-po-kraskih-klancih/trail-po-kraskih-klancih-trasa-2-19.5km.gpx"
  },
  "trail-velika-planina": {
    "dolga-trasa": "/gpx/trail-velika-planina/trail-velika-planina-dolga-trasa-29.5km.gpx",
    "kratka-trasa": "/gpx/trail-velika-planina/trail-velika-planina-kratka-trasa-6.5km.gpx",
    "srednja-trasa": "/gpx/trail-velika-planina/trail-velika-planina-srednja-trasa-13.8km.gpx"
  },
  "ultra-trail-vipava-valley": {
    "asterix": "/gpx/ultra-trail-vipava-valley/ultra-trail-vipava-valley-asterix-15km.gpx",
    "centurion": "/gpx/ultra-trail-vipava-valley/ultra-trail-vipava-valley-centurion-111km.gpx",
    "city-run": "/gpx/ultra-trail-vipava-valley/ultra-trail-vipava-valley-city-run-10km.gpx",
    "emperor": "/gpx/ultra-trail-vipava-valley/ultra-trail-vipava-valley-emperor-162km.gpx",
    "gladiator": "/gpx/ultra-trail-vipava-valley/ultra-trail-vipava-valley-gladiator-60km.gpx",
    "legionar": "/gpx/ultra-trail-vipava-valley/ultra-trail-vipava-valley-legionar-30km.gpx"
  },
  "velenje-trail": {
    "mastodont": "/gpx/velenje-trail/velenje-trail-mastodont-37km.gpx",
    "pozoj": "/gpx/velenje-trail/velenje-trail-pozoj-18km.gpx"
  },
  "zaplana-trail": {
    "cankarjevih-27": "/gpx/zaplana-trail/zaplana-trail-cankarjevih-27-27km.gpx",
    "napoleonovih-4": "/gpx/zaplana-trail/zaplana-trail-napoleonovih-4-4.1km.gpx",
    "rimljanskih-13": "/gpx/zaplana-trail/zaplana-trail-rimljanskih-13-13.5km.gpx"
  },
  "zimski-trail-tek-bohinj": {
    "kratka-trasa-1-krog": "/gpx/zimski-trail-tek-bohinj/zimski-trail-tek-bohinj-kratka-trasa-1-krog-6km.gpx"
  }
}
